version: '3.4'

services:
  webapi:
    image: ${DOCKER_REGISTRY-}webapi
    build:
      context: .
      dockerfile: WebApi/Dockerfile
    ports:
      - "5000:80"
      - "5001:443"
    networks:
      - shared-network

  identityserver:
    image: ${DOCKER_REGISTRY-}identityserver
    build:
      context: .
      dockerfile: IdentityServer/Dockerfile
    ports:
      - "5003:80"
      - "5002:443"
    networks:
      - shared-network

  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_DB: "homework"
      POSTGRES_USER: "tester"
      POSTGRES_PASSWORD: "tester"
      PGDATA: "DockerData/Postgres"
    volumes:
      - .:/var/lib/postgresql/data
      - ./WebApi/DB.Scripts:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G
    networks:
      - shared-network
  rabbitmq:
    container_name: rabbitmq_container
    image: masstransit/rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    
networks:
  shared-network:
    driver: bridge