version: '3.4'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: "homework"
      POSTGRES_USER: "tester"
      POSTGRES_PASSWORD: "tester"
    volumes:
      - ./WebApi/postgre-scripts:/docker-entrypoint-initdb.d
    ports:
      - "5434:5432"
      
  rabbitmq:
    image: masstransit/rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
      
  webapi:
    image: ${DOCKER_REGISTRY-}webapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    build:
      context: .
      dockerfile: WebApi/Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - db
      - rabbitmq
      
  identityserver:
    image: ${DOCKER_REGISTRY-}identityserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    build:
      context: .
      dockerfile: Identity.Api/Dockerfile
    ports:
      - "5001:80"